//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJMicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TaxDetail
    {
        public long taxDetailsId { get; set; }
        public Nullable<long> tId { get; set; }
        public Nullable<decimal> cgst_per { get; set; }
        public Nullable<decimal> cgst_rate { get; set; }
        public Nullable<decimal> sgst_per { get; set; }
        public Nullable<decimal> sgst_rate { get; set; }
        public Nullable<decimal> igst_per { get; set; }
        public Nullable<decimal> igst_rate { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<System.DateTime> uDate { get; set; }
    
        public virtual tbl_TaxMaster tbl_TaxMaster { get; set; }
    }
}
