//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJMicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccLedger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AccLedger()
        {
            this.tbl_PurchaseMaster = new HashSet<tbl_PurchaseMaster>();
            this.tbl_SalesMaster = new HashSet<tbl_SalesMaster>();
            this.tbl_LedgerDetails = new HashSet<tbl_LedgerDetails>();
        }
    
        public long Id { get; set; }
        public long groupId { get; set; }
        public string ledgerName { get; set; }
        public Nullable<decimal> opBalance { get; set; }
        public string opBalanceDC { get; set; }
        public Nullable<int> type { get; set; }
        public string notes { get; set; }
        public Nullable<int> drId { get; set; }
        public Nullable<int> crId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual tbl_AccGroup tbl_AccGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseMaster> tbl_PurchaseMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SalesMaster> tbl_SalesMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LedgerDetails> tbl_LedgerDetails { get; set; }
    }
}
