//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJMicroAccounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StockItemDetails
    {
        public long id { get; set; }
        public Nullable<long> itemId { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> melting { get; set; }
        public Nullable<decimal> carret { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> upadtedDate { get; set; }
    
        public virtual tbl_ItemMaster tbl_ItemMaster { get; set; }
    }
}
